# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Trevor's Tales
author: Trevor Michaelson
description: >- # this means to ignore newlines until "baseurl:"
  A collection of writing (mostly fiction) by Trevor Michaelson. 
url: "https://trevorstales.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

source: src
destination: _site

include: ['src', '_redirects']

collections:
  stories:
    output: true
    permalink: /stories/:title
  blog:
    output: true
    permalink: /blog/:title
  categories:
    output: true
    permalink: /categories/:title

feed:
  collections:
    - stories
    - blog
    
# Asset Manager Configs
assets:
  defaults:
    js: { integrity: false }
    css: { integrity: false }
    img: { integrity: false }
  sources:
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/videos
    - _assets/img
    - _assets/js
    - _assets/vendor
    - uploads
    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
