backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/_assets/img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "stories" # Used in routes, e.g., /admin/collections/blog
    label: "Story" # Used in the UI
    folder: "src/_stories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "story"}
      - {label: "Title", name: "title", widget: "string", default: "Enter Title Here"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "string", default: "uploads/[image-name]"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Categories", name: "categories", widget: "select", multiple: true, options: ['literary', 'short story', 'comedic fiction']}
      - {label: "Body", name: "body", widget: "markdown"}